### ISSUE TITLE
Failed to set capind

### ISSUE THREAD

**Issue by narcisgarcia** [zaf/Asterisk-eSpeak#5]
I've tried by installing Asterisk 13 on Debian 9 these packages: asterisk asterisk-espeak
But when just diaplan runs:
`same => n,Espeak("deje su mensaje",any,es)`
then Asterisk console shows:
`[Jul 31 14:17:14] ERROR[13903][C-00000000]: app_espeak.c:352 espeak_exec: eSpeak: Failed to set capind=0.
Same behaviour `

**Comment by zaf** [comment]
What version of espeak you have installed? What is the output of `dpkg -l espeak`
What is the output of `ldd /usr/lib/asterisk/modules/app_espeak.so`
and what is in your espeak.conf file.

**Comment by narcisgarcia** [comment]
```
$ dpkg -l espeak
dpkg-query: no packages found matching espeak
$ dpkg -l espeak-ng
dpkg-query: no packages found matching espeak-ng
$ dpkg -l asterisk-espeak 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-==================================================================================================
ii  asterisk-espeak                                3.0-3                        i386                         eSpeak module for Asterisk
$ ldd /usr/lib/asterisk/modules/app_espeak.so
	linux-gate.so.1 (0xb77b0000)
	libespeak-ng.so.1 => /usr/lib/i386-linux-gnu/libespeak-ng.so.1 (0xb7721000)
	libsamplerate.so.0 => /usr/lib/i386-linux-gnu/libsamplerate.so.0 (0xb75b5000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb73fe000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb73e1000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb738c000)
	libpcaudio.so.0 => /usr/lib/i386-linux-gnu/libpcaudio.so.0 (0xb7386000)
	libsonic.so.0 => /usr/lib/i386-linux-gnu/libsonic.so.0 (0xb7380000)
	/lib/ld-linux.so.2 (0x410ae000)
	libasound.so.2 => /usr/lib/i386-linux-gnu/libasound.so.2 (0xb725c000)
	libpulse-simple.so.0 => /usr/lib/i386-linux-gnu/libpulse-simple.so.0 (0xb7254000)
	libpulse.so.0 => /usr/lib/i386-linux-gnu/libpulse.so.0 (0xb71fa000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb71f5000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb71ec000)
	libpulsecommon-10.0.so => /usr/lib/i386-linux-gnu/pulseaudio/libpulsecommon-10.0.so (0xb715d000)
	libcap.so.2 => /lib/i386-linux-gnu/libcap.so.2 (0xb7157000)
	libdbus-1.so.3 => /lib/i386-linux-gnu/libdbus-1.so.3 (0xb70fb000)
	libX11-xcb.so.1 => /usr/lib/i386-linux-gnu/libX11-xcb.so.1 (0xb70f8000)
	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xb6faa000)
	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xb6f7e000)
	libICE.so.6 => /usr/lib/i386-linux-gnu/libICE.so.6 (0xb6f5f000)
	libSM.so.6 => /usr/lib/i386-linux-gnu/libSM.so.6 (0xb6f55000)
	libXtst.so.6 => /usr/lib/i386-linux-gnu/libXtst.so.6 (0xb6f4d000)
	libsystemd.so.0 => /lib/i386-linux-gnu/libsystemd.so.0 (0xb6ebb000)
	libwrap.so.0 => /lib/i386-linux-gnu/libwrap.so.0 (0xb6eb0000)
	libsndfile.so.1 => /usr/lib/i386-linux-gnu/libsndfile.so.1 (0xb6e23000)
	libasyncns.so.0 => /usr/lib/i386-linux-gnu/libasyncns.so.0 (0xb6e1c000)
	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xb6e18000)
	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xb6e11000)
	libbsd.so.0 => /lib/i386-linux-gnu/libbsd.so.0 (0xb6df5000)
	libuuid.so.1 => /lib/i386-linux-gnu/libuuid.so.1 (0xb6def000)
	libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xb6dd8000)
	libXi.so.6 => /usr/lib/i386-linux-gnu/libXi.so.6 (0xb6dc5000)
	libselinux.so.1 => /lib/i386-linux-gnu/libselinux.so.1 (0xb6d98000)
	liblzma.so.5 => /lib/i386-linux-gnu/liblzma.so.5 (0xb6d6c000)
	liblz4.so.1 => /usr/lib/i386-linux-gnu/liblz4.so.1 (0xb6d59000)
	libgcrypt.so.20 => /lib/i386-linux-gnu/libgcrypt.so.20 (0xb6c8a000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb6c6c000)
	libnsl.so.1 => /lib/i386-linux-gnu/libnsl.so.1 (0xb6c52000)
	libFLAC.so.8 => /usr/lib/i386-linux-gnu/libFLAC.so.8 (0xb6bf3000)
	libogg.so.0 => /usr/lib/i386-linux-gnu/libogg.so.0 (0xb6bea000)
	libvorbis.so.0 => /usr/lib/i386-linux-gnu/libvorbis.so.0 (0xb6bbe000)
	libvorbisenc.so.2 => /usr/lib/i386-linux-gnu/libvorbisenc.so.2 (0xb6b30000)
	libresolv.so.2 => /lib/i386-linux-gnu/libresolv.so.2 (0xb6b18000)
	libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xb6a9f000)
	libgpg-error.so.0 => /lib/i386-linux-gnu/libgpg-error.so.0 (0xb6a88000)
$ cat /etc/asterisk/espeak.conf | grep -ve '^;'
[general]
[voice]
```

**Comment by zaf** [comment]
So you are using the debian package. As it looks it is linked against espeak-ng. I haven't tested against this and I can't suggest anything, maybe the ng library has somehow broke the backwards compatibility with plain espeak. I would suggest opening a bug on debian for this. Meanwhile you can try removing the package, installing espeak and building the module from source.

**Comment by narcisgarcia** [comment]
I've now tried with installing espeak but also no luck. Uninstalling it and installing espeak-ng again and still no luck. Note that original espeak is totally unmaintained and probably will be dropped in the future from repositories.

libespeak-ng.so is provided by libespeak-ng1 package, and package asterisk-espeak depends on libespeak-ng1

Isn't there any way to debug the cause of error to later try use repository's packages with some discovered workaround?

**Comment by zaf** [comment]
Installing epseak alone wont change anything, what I suggested was to get the source and compile the asterisk module. 

I'm aware that espeak is on its way out but I didn't had the time yet to test and port the module to using espeak-ng, it is on my todo list.

**Comment by zaf** [comment]
It looks like the failure to set the `capind` parameter is an espeak-ng upstream bug, but I dont really have time to investigate further. I pushed an [update](https://github.com/zaf/Asterisk-eSpeak/commit/b1a260b6d43f110a7f28c5b60bde34a3620cbf7b) that uses esepak-ng but removes the ability to set the `capind` parameter, it was a rather obscure feature anyway.
Everything else seems to work based on some very basic testing i did, but please keep in mind that this is still `beta` and also only works for very recent versions of asterisk (I tested only against asterisk 15).

**Comment by narcisgarcia** [comment]
Thank you anyway for working on it.
Note that [Next Debian version](https://packages.debian.org/buster/asterisk-espeak) is still not upgrading to Asterisk 15.
If at some moment your tests of asterisk-espeak work with Asterisk 13, then I'll try to ask Debian package maintainers to update package with your patch.

**Comment by zaf** [comment]
Just an update on this, the current tag on the master branch of the repo (v5.0-rc1) with the espeak-ng patches and fixes seems to work fine with asterisk 13 on Debian.
